version: "3.9"

# nd - navigation devices

services:
  api:
    container_name: nd_api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      PORT: ${API_PORT:-8080}
    ports:
      - "${API_PORT:-8080}:8080"
    networks:
      - nd-net

  postgres:
    container_name: nd_postgres
    image: postgres:14
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE:-nd_db}
      POSTGRES_DATABASE_HOST: ${POSTGRES_DATABASE_HOST:-nd_postgres}
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    networks:
      - nd-net
    restart: unless-stopped

  pgadmin:
    container_name: nd_pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - nd-net
    restart: unless-stopped

networks:
  nd-net:
    driver: bridge
